<?php

//CMS应用参数配置
return array(
	'actionInfo'=>array(
		'saveSuccess'=>'信息添加成功！请继续添加。',
		'saveFail'=>'信息添加失败！请重新添加。',
		'updateSuccess'=>'信息更新成功！',
		'updateFail'=>'信息更新失败！请重新保存。',
		'deleteSuccess'=>'信息删除成功！',
		'deleteFail'=>'信息删除失败！',
	),
	'role'=>array(
		'1'=>'超级管理员',
		'2'=>'网站管理员',
		'3'=>'网站会员',
	),
	'roleact'=>array(
		'article_create'=>array(
			'1'=>true,
			'2'=>true,
			'3'=>true,
		)
	),
	'feedback'=>array(
		'1'=>'网站留言'
	),
	'girdpagesize'=>15,
	'menuoption'=>array(
		'content'=>array(
			'article'=>true,
			'product'=>true,
			'link'=>true,
			'picture'=>true,
			'feedback'=>true,
			'job'=>true,
		),
	),
	'seo'=>false,
	'urltarget'=>array(
		'_blank'=>'在新页面打开',
		'_self'=>'在当前页打开',
	),
	'recommend'=>array(
		'article_display'=>false,
		'product_display'=>false,
		'article'=>array(
			'0'=>'请选择',
			'1'=>'推荐',
		),
		'product'=>array(
			'0'=>'请选择',
			'1'=>'推荐',
		),
	),
	'recommend_level'=>array(
		'article_display'=>false,
		'product_display'=>false,
		'article'=>array(
			'0'=>'请选择',
			'1'=>'1',
			'2'=>'2',
			'3'=>'3',
			'4'=>'4',
			'5'=>'5',
			'6'=>'6',
			'7'=>'7',
			'8'=>'8',
			'9'=>'9',
		),
		'product'=>array(
			'0'=>'请选择',
			'1'=>'1',
			'2'=>'2',
			'3'=>'3',
			'4'=>'4',
			'5'=>'5',
			'6'=>'6',
			'7'=>'7',
			'8'=>'8',
			'9'=>'9',
		),
	),
);
